on:
  workflow_dispatch:
jobs:
  hello-my-actions:
    runs-on: ubuntu-latest
    name: Cloudtype Init
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: init
        uses: ./
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}
          readOnly: true
